# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: 127.0.0.1
  database: snippet_drawer_development
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  adapter: postgresql
  host: 127.0.0.1
  database: snippet_drawer_test
  pool: 5
  timeout: 5000
  username: postgres
  password: password

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
